lido-chain:
  chain-prefix: "cosmos"
  rpc-address: "tcp://127.0.0.1:26657"
  chain-id: "testnet"
  gas-prices: "0.5stake"
  tx-broadcast-type: "BroadcastTxCommit"
  keyring-dir: ""
  sign-key-name: ""
target-chain:
  account-prefix: "osmo"
  validator-account-prefix: "osmovaloper"
  rpc-address: "tcp://52.9.216.144:26657"
  chain-id: "osmosis-1"
  timeout: "10s"
