lido-chain:
  chain-prefix: "cosmos"
  rpc-address: "tcp://127.0.0.1:26657"
  chain-id: "testnet"
  gas-prices: "0.5stake"
  tx-broadcast-type: "BroadcastTxCommit"
  event-subscriber-name: "cosmos-query-relayer"
  keyring-dir: ""
  sign-key-name: ""
target-chain:
  chain-prefix: "terra"
  rpc-address: "tcp://public-node.terra.dev:26657"
  chain-id: "columbus-5"
