neutron-chain:
  chain-prefix: "neutron"
  rpc-address: "tcp://127.0.0.1:16657"
  chain-id: "test-1"
  gas-prices: "0.5stake"
  tx-broadcast-type: "BroadcastTxCommit"
  event-subscriber-name: "cosmos-query-relayer"
  home-dir: "../neutron/data/test-1"
  sign-key-name: "demowallet1"
  connection-id: "connection-0"
  client-id: "07-tendermint-0"
  chain-provider-config-path: "./configs/chains/neutron.json"

target-chain:
  account-prefix: "neutron"
  validator-account-prefix: "neutronvaloper"
  rpc-address: "tcp://127.0.0.1:26657"
  chain-id: "test-2"
  home-dir: "../neutron/data/test-2"
  connection-id: "connection-0"
  client-id: "07-tendermint-0"
  chain-provider-config-path: "./configs/chains/target.json"