lido-chain:
  chain-prefix: "cosmos"
  rpc-address: "tcp://127.0.0.1:16657"
  chain-id: "test-1"
  gas-prices: "0.5stake"
  tx-broadcast-type: "BroadcastTxCommit"
  event-subscriber-name: "cosmos-query-relayer"
  home-dir: "../interchain-adapter/data/test-1"
  sign-key-name: "demowallet1"
  chain-provider-config-path: "./configs/chains/lido.json"

target-chain:
  chain-prefix: "cosmos"
  rpc-address: "tcp://127.0.0.1:26657"
  chain-id: "test-2"
  home-dir: "../interchain-adapter/data/test-2"
  chain-provider-config-path: "./configs/chains/target.json"